# This workflow will execute tests on PRs to master branch.
# It will perform actions parallely on macos, ubuntu environments.
# Currently, it fails to run on windows using matrix windows-latest.
# Additionally, it becomes unstable to run on ubuntu using matrix ubuntu-latest.

name: Run tests on PRs
on:
  pull_request:
    branches: [ "master" ]
    
permissions:
  contents: read
  
jobs:
  test:
    strategy:
      matrix:
        os: [macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17
        
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    
    - name: Execute Gradle test
      run: ./gradlew test
